name: Game of life testing

on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Esto permite que todos los jobs terminen, aunque uno falle
      matrix:
        java: [ '17', '21' ]  # Define las versiones de Java que queremos probar

    steps:
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Java version
        run: java -version
      - name: Maven version
        run: mvn --version
      - name: Maven test
        run: mvn test

